# Shell variables
# Generated by 'wal'
wallpaper='/home/vic/Pictures/Anime/Senjougahara/senjougahara_vector_art_wallpaper_by_walidsodki_da9p9fa-pre.jpg'

# Special
background='#241d35'
foreground='#ccdfeb'
cursor='#ccdfeb'

# Colors
color0='#241d35'
color1='#5990E8'
color2='#619FE6'
color3='#67B1F0'
color4='#8E89B7'
color5='#A6A0D1'
color6='#C7B8C1'
color7='#ccdfeb'
color8='#8e9ca4'
color9='#5990E8'
color10='#619FE6'
color11='#67B1F0'
color12='#8E89B7'
color13='#A6A0D1'
color14='#C7B8C1'
color15='#ccdfeb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
